### ISSUE TITLE
Failure to load

### ISSUE THREAD

**Issue by scargill** [voidpp/PCA9685-driver#2]
pip install PCA9685-driver
Collecting PCA9685-driver
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connec                                    tion broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.conne                                    ction.VerifiedHTTPSConnection object at 0xffffabd5f390>: Failed to establish a n                                    ew connection: [Errno -3] Temporary failure in name resolution',)': /simple/pca9                                    685-driver/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connec                                    tion broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.conne                                    ction.VerifiedHTTPSConnection object at 0xffffabd5fa50>: Failed to establish a n                                    ew connection: [Errno -3] Temporary failure in name resolution',)': /simple/pca9                                    685-driver/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xffffabd5ff10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/pca9685-driver/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xffffabd5f750>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/pca9685-driver/

**Comment by voidpp** [comment]
This issue about pip, or your connections, not this package
